{% set version = '1.1-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-crossdes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/crossdes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/crossdes/crossdes_{{ version }}.tar.gz
  sha256: 5e65e760bf22fc07036c69ceb462dddb97605cae0e8e3cdac503d43a50938959

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-algdesign
    - r-gtools
  run:
    - r-base
    - r-algdesign
    - r-gtools

test:
  commands:
    - $R -e "library('crossdes')"           # [not win]
    - "\"%R%\" -e \"library('crossdes')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=crossdes
  license: GPL-2.0-only
  summary: Contains functions for the construction of carryover balanced crossover designs. In
    addition contains functions to check given designs for balance.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - aspencage
# Package: crossdes
# Date: 2022-04-04
# Title: Construction of Crossover Designs
# Version: 1.1-2
# Author: Martin Oliver Sailer
# Depends: AlgDesign, gtools
# Description: Contains functions for the construction of carryover balanced crossover designs. In addition contains functions to check given designs for balance.
# Maintainer: Bjoern Bornkamp <bbnkmp@mail.de>
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2022-04-04 18:57:03 UTC; bjoern
# Repository: CRAN
# Date/Publication: 2022-04-04 21:50:02 UTC
